#!/bin/sh

if [ ! -f resources/public/js/webppl-v0.9.11.js ]; then
   cd resources/public/js/
   wget http://cdn.webppl.org/webppl-v0.9.11.js
   mv webppl-v0.9.11.js webppl-v0.9.11.js.gz
   gunzip webppl-v0.9.11.js.gz
   cd ../../../
fi

cp resources/public/js/webppl-v0.9.11.js unit-test.js
cat resources/private/js/unit-test.js >> unit-test.js

phantomjs unit-test.js
